# print("\033[1;34;48m Salut je suis du bright blue\033")
print('-------------------------')
print('DEDALE')
print('-------------------------')
print('')
print('1 - JOUER')
print('2 - CHARGER')
print('3 - INSTRUCTIONS')
print('4 - CREDITS')
print('5 - QUITTER')
print('')
print('Appuyez sur la touche correspondante')

